name: Release PR Checklist
on:
    pull_request:
        types: [opened, reopened, synchronize]
jobs:
    comment:
        if: github.event.pull_request.title == 'Version Packages'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/github-script@v7
              with:
                  script: |
                      const body = `### Release Checklist
                      - [ ] Verify CHANGELOG summaries match Sprint scope.
                      - [ ] Link to Roadmap section and Sprint docs.
                      - [ ] Confirm dist-tag:
                        - Stable: \`latest\`
                        - Beta (pre mode): \`beta\` via \`pnpm -w changeset publish --tag beta\`
                      - [ ] Sanity-pack all packages: \`npm pack --workspaces\`
                      - [ ] Docs site updated (if API or user-facing changes)
                      - [ ] Examples updated
                      - [ ] Breaking changes documented with migration notes
                      `;
                      await github.rest.issues.createComment({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: context.payload.pull_request.number,
                        body
                      });
